server:  
  port: ${PORT:8761}
    
eureka:  
  instance:
#local
    hostname: localhost
#dev
#    hostname: 192.168.100.11
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  server:
    enableSelfPreservation: true
    peer-node-read-timeout-ms: 160000000
    registry-sync-retry-wait-ms: 500
    registry-sync-retries: 3
    a-s-g-cache-expiry-timeout-ms: 60000
    eviction-interval-timer-in-ms: 30000
    peer-eureka-nodes-update-interval-ms: 15000
    renewal-threshold-update-interval-ms: 300000
    wait-time-in-ms-when-sync-empty: 0
    max-threads-for-peer-replication: 0
management:
  endpoints:
    jmx:
      unique-names: true
spring:
  application:
    name: eureka-service  jmx:
    enabled: false
#    default-domain: ${spring.application.name} 