spring:  
  application:
    name: business
  data:
#config mongo DB log
    mongodb:
      host: 192.168.100.201
      port: 27017
      username: cobdblog
      password: cobdblog
      database: cobdblog
      authentication-database: cobdblog
      collectionrefix: business_
      collectiondetailrefix: business_detail_
#config postgresql DB 
  datasource:
    url: jdbc:postgresql://192.168.100.201:5432/cob
    username: dbcob
    password: 123456
  jpa:
    properties:
      hibernate:
        default_schema: mdl_business
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jmx:
    default_domain: business
    enabled: false
#    database-platform:  org.hibernate.dialect.PostgreSQL95Dialect
#    show-sql: true
    
server:  
  port: ${PORT:8060}  
#config register discovery enakena service
eureka:  
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
#localhost
#      defaultZone: ${DISCOVERY_URL:http://localhost:8761/cobregister}/eureka/
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
#dev
#      defaultZone: ${DISCOVERY_URL:http://192.168.100.201:8761}/eureka/
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
#config register enable r enakena service          
ribbon:
  eureka:
    enabled: true
    hystrix: 
  command:
    default: 
      execution:
        timeout:
          enabled: false
          
feign:
  client:
    config: 
      default:
        connectTimeout: 160000000
        readTimeout: 160000000 